(require :asdf)
(asdf:load-asd (truename "runtime/starintel-edge.asd"))
(asdf:load-system "starintel-edge/mesh-runtime")
(load "tests/mesh.lisp")
(in-package #:star.edge.mesh)
(defun wait-for (predicate &optional (seconds 2))
  (let ((deadline (+ (get-internal-real-time) (* seconds internal-time-units-per-second))))
    (loop until (funcall predicate)
          do (when (>= (get-internal-real-time) deadline) (error "Test wait timeout")) (sleep 0.005))))
(defclass reflecting-transport (synthetic-transport) ())
(defmethod transport-send ((port reflecting-transport) peer frames &optional route)
  (declare (ignore route))
  (multiple-value-bind (request result) (decode-message frames 65536)
    (unless result
      (push (make-delivery :peer peer :frames (encode-message request (make-result :ok (request-payload request))))
            (inbox port))))
  :sent)
(let ((star.edge.runtime:*require-confirmed-shutdown* t)
      (star.edge.runtime:*redact-diagnostics* t)
      (port (make-instance 'reflecting-transport)))
  (multiple-value-bind (component handle) (make-mesh-component (runtime port :config (config :max-pending 1)))
    (let ((rt (star.edge.runtime:start-runtime (list component))))
      (unwind-protect
           (progn
             (check (eq :running (star.edge.runtime:runtime-state rt)))
             (check (eq :running (getf (mesh-component-status handle) :state)))
             (let ((ticket (submit-to-mesh handle "peer-a" (request))) (result nil))
               (check (mesh-ticket-p ticket))
               (check (eq :overloaded (result-status (submit-to-mesh handle "peer-a" (request :id "other")))))
               (wait-for (lambda () (setf result (take-mesh-result handle ticket))))
               (check (eq :ok (result-status result)))
               (check (equalp (bytes "opaque") (result-payload result)))))
        (check (star.edge.runtime:stop-runtime rt)))
      (check (closed port))
      (check (not (bordeaux-threads:thread-alive-p (mesh-component-handle-thread handle))))
      ;; Repeated managed start/stop uses a fresh owned thread, never a second live owner.
      (let ((again (star.edge.runtime:start-runtime (list component))))
        (check (eq :running (star.edge.runtime:runtime-state again)))
        (check (star.edge.runtime:stop-runtime again))))))

(defclass provider-transport (synthetic-transport) ())
(defmethod transport-open ((port provider-transport) config provider)
  (declare (ignore config)) (funcall provider "test-ref") (setf (closed port) nil) t)
;; A blocked provider may not be killed unsafely or dropped from lifecycle ownership.
(let* ((lock (bordeaux-threads:make-lock "blocked-provider")) (released nil) (calls 0)
       (port (make-instance 'provider-transport))
       (mesh (make-mesh :config (config) :transport port
                       :credential-provider (lambda (reference)
                                              (declare (ignore reference))
                                              (bordeaux-threads:with-lock-held (lock) (incf calls))
                                              (loop until (bordeaux-threads:with-lock-held (lock) released) do (sleep 0.005))
                                              nil)))
       (star.edge.runtime:*require-confirmed-shutdown* t)
       (star.edge.runtime:*redact-diagnostics* t))
  (multiple-value-bind (component handle) (make-mesh-component mesh :timeout-seconds 0.1)
    (let ((rt (handler-bind ((warning #'muffle-warning)) (star.edge.runtime:start-runtime (list component)))))
      (unwind-protect
           (progn
             (check (eq :stop-failed (star.edge.runtime:runtime-state rt)))
             (check (= calls 1))
             (check (bordeaux-threads:thread-alive-p (mesh-component-handle-thread handle)))
             (check (rejects (lambda () (star.edge.runtime:start-runtime (list component)))))
             (check (rejects (lambda () (start-mesh-component handle 0.1))))
             (check (= calls 1)))
        (bordeaux-threads:with-lock-held (lock) (setf released t))
        (wait-for (lambda () (not (bordeaux-threads:thread-alive-p (mesh-component-handle-thread handle)))))
        (check (star.edge.runtime:stop-runtime rt)))
      (check (eq :stopped (star.edge.runtime:runtime-state rt))))))

;; Startup conditions are reduced to stable status, no provider secret marker.
(let* ((port (make-instance 'provider-transport))
       (mesh (make-mesh :config (config) :transport port
                       :credential-provider (lambda (reference) (declare (ignore reference))
                                              (error "MESH-SECRET-MARKER")))))
  (check (eq :unavailable (getf (start-mesh mesh) :state)))
  (check (not (search "MESH-SECRET-MARKER" (write-to-string (mesh-status mesh)))))
  (check (closed port)))
(format t "~D checks including real managed owner/thread lifecycle over synthetic transport; no sockets/device claim.~%" *checks*)
