(load "runtime/mesh-package.lisp")
(load "runtime/mesh.lisp")
(in-package #:star.edge.mesh)
(defvar *checks* 0)
(defun check (value &optional (message "check failed"))
  (incf *checks*) (unless value (error "~A (check ~D)" message *checks*)))
(defun rejects (thunk) (handler-case (progn (funcall thunk) nil) (error () t)))
(defun bytes (text) (ascii-octets text))

;; An explicit synthetic transport. No cryptography, socket or hardware evidence.
(defclass synthetic-transport (transport)
  ((inbox :initform nil :accessor inbox) (sent :initform nil :accessor sent)
   (send-result :initform :sent :accessor send-result) (closed :initform nil :accessor closed)
   (receiver :initform nil :accessor receiver) (identity :initarg :identity :initform "peer-a" :reader identity-of)))
(defmethod transport-open ((port synthetic-transport) config provider)
  (declare (ignore config provider)) (setf (closed port) nil) t)
(defmethod transport-close ((port synthetic-transport)) (setf (closed port) t))
(defmethod transport-send ((port synthetic-transport) peer frames &optional route)
  (when (eq (send-result port) :throw) (error "synthetic partial send"))
  (when (eq (send-result port) :sent)
    (push (list peer (mapcar #'copy-seq frames) route) (sent port))
    (when (receiver port)
      (setf (inbox (receiver port))
            (append (inbox (receiver port))
                    (list (make-delivery :peer (identity-of port) :route (bytes "route")
                                         :frames (mapcar #'copy-seq frames)))))))
  (send-result port))
(defmethod transport-poll ((port synthetic-transport))
  (prog1 (inbox port) (setf (inbox port) nil)))
(defun peer (&optional (id "peer-a"))
  (make-peer :id id :endpoint "tcp://127.0.0.1:49101" :key-reference "key-a"
             :callers '("star:v1:projector:client") :actors '("star:v1:resolver:echo")))
(defun config (&rest overrides)
  (apply #'make-config
         (append overrides (list :node-id "local" :bind-endpoint "tcp://127.0.0.1:49100"
                                 :credential-reference "local-key" :peers (list (peer))
                                 :operations (list (make-operation :name "star.edge.echo" :retry-safe t)
                                                   (make-operation :name "star.edge.mutate"))))))
(defun request (&rest overrides)
  (apply #'make-request (append overrides
                        (list :id "request-1" :caller "star:v1:projector:client"
                              :destination "star:v1:resolver:echo" :operation "star.edge.echo"
                              :payload (bytes "opaque") :deadline 5000))))
(defun runtime (port &key (config (config)) (clock (lambda () 1000))
                         (authorize (lambda (&rest args) (declare (ignore args)) t))
                         (dispatch (lambda (peer req) (declare (ignore peer)) (lambda () (make-result :ok (request-payload req))))))
  (make-mesh :config config :transport port :credential-provider (lambda (&rest args) (declare (ignore args)) nil)
             :clock clock :authorize authorize :dispatch dispatch))
(defun deliver (port req &optional (peer "peer-a") result)
  (push (make-delivery :peer peer :route (bytes "route") :frames (encode-message req result)) (inbox port)))
(defun last-status (port)
  (when (sent port) (multiple-value-bind (req result) (decode-message (second (first (sent port))) 65536)
                     (declare (ignore req)) (and result (result-status result)))))

;; Configuration rejects public and implicit endpoints, invalid scopes and unbounded state.
(dolist (endpoint '("tcp://0.0.0.0:9000" "tcp://8.8.8.8:9000" "tcp://example.com:9000"
                    "tcp://*:9000" "ipc:///tmp/socket" "tcp://127.0.0.1:0" "tcp://127.0.0.1:65536"
                    "tcp://127.00.0.1:5000" "tcp://127.0.0.1:2x" "tcp://192.169.1.2:9000"))
  (check (not (private-endpoint-p endpoint))))
(dolist (endpoint '("tcp://127.0.0.1:5000" "tcp://10.1.2.3:5000" "tcp://172.16.0.1:5000"
                    "tcp://172.31.1.2:5000" "tcp://192.168.1.1:5000"))
  (check (private-endpoint-p endpoint)))
(check (rejects (lambda () (config :mode :public-swarm))))
(check (rejects (lambda () (config :max-pending 0))))
(check (rejects (lambda () (config :max-message-bytes 1048577))))
(check (rejects (lambda () (config :peers (list (peer) (peer))))))
(check (rejects (lambda () (make-peer :id "x" :endpoint "tcp://127.0.0.1:1"
                                     :key-reference "ref" :actors '("../eval")))))
(check (equal :unavailable (getf (start-mesh (make-mesh :config (config))) :state)))

;; Opaque payloads preserve canonical JSON-LD bytes and false/null. No new document schema.
(let* ((payload (bytes "{\"schemaVersion\":\"0.10.1\",\"deleted\":false,\"extensions\":{\"opaque\":null}}"))
       (req (request :payload payload :correlation "parent" :causation "cause" :trace "trace"
                     :authorization-context "receipt" :idempotency-key "application-key"))
       (frames (encode-message req)) (decoded (decode-message frames 65536)))
  (check (equalp payload (request-payload decoded)))
  (check (equalp frames (encode-message decoded)))
  (check (not (eq payload (request-payload decoded))))
  (dolist (frames (list (butlast frames) (append frames (list (bytes "extra")))
                       (cons (bytes "wrong") (rest frames))))
    (check (rejects (lambda () (decode-message frames 65536)))))
  (dolist (index '(1 2 9 14 15 16))
    (let ((bad (copy-list frames)))
      (setf (nth index bad) (bytes "bad"))
      (check (rejects (lambda () (decode-message bad 65536))))))
  (check (rejects (lambda () (decode-message frames 20))))
  (let ((bad (copy-list frames)))
    (setf (nth 7 bad) (make-array 1 :element-type '(unsigned-byte 8) :initial-element 255))
    (check (rejects (lambda () (decode-message bad 65536))))))

;; Scoped routing, unknown peer rejection, malformed messages and no code interpretation.
(let* ((calls 0) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :dispatch (lambda (peer req) (declare (ignore peer)) (incf calls)
                                      (lambda () (make-result :ok (request-payload req)))))))
  (start-mesh mesh)
  (deliver port (request :payload (bytes "#.(error \"never evaluate\")")))
  (step-mesh mesh)
  (check (= 1 calls)) (check (eq :ok (last-status port)))
  (deliver port (request)) ; same ID, altered bytes => conflict, no dispatch
  (step-mesh mesh) (check (eq :conflict (last-status port))) (check (= 1 calls))
  (deliver port (request :payload (bytes "#.(error \"never evaluate\")")))
  (step-mesh mesh) (check (eq :ok (last-status port))) (check (= 1 calls))
  (deliver port (request :id "forged") "unknown-key-peer")
  (let ((count (length (sent port)))) (step-mesh mesh) (check (= count (length (sent port)))))
  (deliver port (request :id "wrong-actor" :destination "star:v1:collector:private"))
  (step-mesh mesh) (check (eq :forbidden (last-status port)))
  (deliver port (request :id "wrong-caller" :caller "star:v1:orchestrator:root"))
  (step-mesh mesh) (check (eq :forbidden (last-status port)))
  (deliver port (request :id "expired" :deadline 900))
  (step-mesh mesh) (check (eq :deadline-exceeded (last-status port)))
  (deliver port (request :id "unknown-op" :operation "lisp.eval"))
  (step-mesh mesh) (check (eq :invalid (last-status port)))
  (check (= 1 calls))
  (push (make-delivery :peer "peer-a" :frames (list (bytes "invalid"))) (inbox port))
  (step-mesh mesh) (check (= 1 calls))
  (stop-mesh mesh) (check (closed port))
  (check (eq :stopped (getf (stop-mesh mesh) :state))))

;; Deny defaults and live revocation apply even to replay and result delivery.
(let* ((port (make-instance 'synthetic-transport)) (allowed t) (calls 0)
       (mesh (runtime port :authorize (lambda (&rest ignored) (declare (ignore ignored)) allowed)
                      :dispatch (lambda (peer req) (declare (ignore peer)) (incf calls) (lambda () (make-result :ok (request-payload req)))))))
  (start-mesh mesh) (deliver port (request)) (step-mesh mesh)
  (setf allowed nil) (deliver port (request)) (step-mesh mesh)
  (check (eq :forbidden (last-status port))) (check (= 1 calls))
  (check (eq :forbidden (result-status (submit-request mesh "peer-a" (request :id "outbound")))))
  (setf allowed :truthy) (deliver port (request)) (step-mesh mesh)
  (check (eq :forbidden (last-status port))))

;; Bounded request/result retention, correlation, read-only retries and mutation ambiguity.
(let* ((now 1000) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :config (config :max-pending 1) :clock (lambda () now))))
  (start-mesh mesh)
  (check (eq :pending (submit-request mesh "peer-a" (request))))
  (check (eq :conflict (result-status (submit-request mesh "peer-a" (request)))))
  (check (eq :overloaded (result-status (submit-request mesh "peer-a" (request :id "second")))))
  (setf now 2100) (step-mesh mesh) (check (= 2 (length (sent port))))
  (deliver port (request) "unknown-peer" (make-result :ok (bytes "spoof")))
  (step-mesh mesh) (check (null (take-result mesh "request-1")))
  (deliver port (request :correlation "wrong") "peer-a" (make-result :ok))
  (step-mesh mesh) (check (null (take-result mesh "request-1")))
  (deliver port (request) "peer-a" (make-result :ok (bytes "actual")))
  (step-mesh mesh)
  (let ((result (take-result mesh "request-1")))
    (check (eq :ok (result-status result))) (check (equalp (bytes "actual") (result-payload result))))
  (check (eq :pending (submit-request mesh "peer-a" (request :id "mutation" :operation "star.edge.mutate"))))
  (let ((count (length (sent port)))) (setf now 4000) (step-mesh mesh) (check (= count (length (sent port)))))
  (setf now 5001) (step-mesh mesh)
  (check (eq :outcome-unknown (result-status (take-result mesh "mutation")))))

;; Pending work retains capacity after expiry, not an unlimited timed-out actor queue.
(let* ((now 1000) (done nil) (calls 0) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :config (config :max-inbound 1 :max-replay 1) :clock (lambda () now)
                      :dispatch (lambda (peer req) (declare (ignore peer)) (declare (ignore req)) (incf calls)
                                  (lambda () (when done (make-result :ok)))))))
  (start-mesh mesh) (deliver port (request :deadline 2000)) (step-mesh mesh)
  (deliver port (request :deadline 2000)) (step-mesh mesh) (check (= 1 calls))
  (setf now 2500)
  (deliver port (request :id "second" :deadline 5000)) (step-mesh mesh)
  (check (eq :overloaded (last-status port))) (check (= 1 calls))
  (setf done t) (step-mesh mesh) (step-mesh mesh)
  (check (zerop (getf (mesh-status mesh) :replay-entries)))
  (deliver port (request :deadline 2000)) (step-mesh mesh)
  (check (eq :deadline-exceeded (last-status port))) (check (= 1 calls)))

;; Saturated/failed sockets and lifecycle never claim delivery or cancellation.
(let* ((port (make-instance 'synthetic-transport)) (mesh (runtime port)))
  (start-mesh mesh) (setf (send-result port) :overloaded)
  (check (eq :overloaded (result-status (submit-request mesh "peer-a" (request)))))
  (check (zerop (getf (mesh-status mesh) :pending)))
  (setf (send-result port) :throw)
  (check (eq :outcome-unknown (result-status (submit-request mesh "peer-a" (request :operation "star.edge.mutate")))))
  (check (closed port)) (check (eq :unavailable (getf (mesh-status mesh) :state)))
  (setf (send-result port) :sent) (resume-mesh mesh)
  (check (eq :pending (submit-request mesh "peer-a" (request :operation "star.edge.mutate"))))
  (suspend-mesh mesh) (check (eq :suspended (getf (mesh-status mesh) :state)))
  (check (eq :outcome-unknown (result-status (take-result mesh "request-1")))))


;; Fatal batch send stops later dispatch; exception text never appears on wire/status.
(let* ((calls 0) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :dispatch (lambda (peer req) (declare (ignore peer req)) (incf calls) nil))))
  (start-mesh mesh) (setf (send-result port) :throw)
  (setf (inbox port) (list (make-delivery :peer "peer-a" :frames (encode-message (request :operation "invalid")))
                          (make-delivery :peer "peer-a" :frames (encode-message (request :operation "star.edge.mutate")))))
  (step-mesh mesh) (check (zerop calls)) (check (eq :unavailable (getf (mesh-status mesh) :state))))
(dolist (where '(:dispatch :poll))
  (let* ((port (make-instance 'synthetic-transport))
         (mesh (runtime port :config (config :max-inbound 1 :max-replay 1)
                        :dispatch (lambda (peer req) (declare (ignore peer req))
                                    (when (eq where :dispatch) (error "MESH-SECRET-MARKER"))
                                    (lambda () (error "MESH-SECRET-MARKER"))))))
    (start-mesh mesh) (deliver port (request :operation "star.edge.mutate")) (step-mesh mesh)
    (check (eq :outcome-unknown (last-status port)))
    (check (not (search "MESH-SECRET-MARKER" (write-to-string (mesh-status mesh)))))
    (check (every (lambda (packet) (every (lambda (frame)
                                          (not (search (bytes "MESH-SECRET-MARKER") frame)))
                                        (second packet))) (sent port)))
    (deliver port (request :id "over-capacity")) (step-mesh mesh)
    (check (eq :overloaded (last-status port)))))
;; Result retry stays bounded and never repeats actor execution, including mutations.
(let* ((now 1000) (calls 0) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :clock (lambda () now)
                      :dispatch (lambda (peer req) (declare (ignore peer req)) (incf calls)
                                  (lambda () (make-result :ok))))))
  (start-mesh mesh) (setf (send-result port) :overloaded)
  (deliver port (request :operation "star.edge.mutate")) (step-mesh mesh)
  (check (= calls 1)) (check (null (sent port)))
  (setf now 2100 (send-result port) :sent) (step-mesh mesh)
  (check (eq :ok (last-status port))) (check (= 1 calls))
  (let ((count (length (sent port)))) (step-mesh mesh) (check (= count (length (sent port))))))
;; Authorization can be revoked while the response is backpressured.
(let* ((allowed t) (now 1000) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :clock (lambda () now)
                      :authorize (lambda (&rest ignored) (declare (ignore ignored)) allowed)
                      :dispatch (lambda (peer req) (declare (ignore peer req))
                                  (lambda () (make-result :ok (bytes "private-response")))))))
  (start-mesh mesh) (setf (send-result port) :overloaded)
  (deliver port (request :operation "star.edge.mutate")) (step-mesh mesh)
  (setf allowed nil now 2100 (send-result port) :sent) (step-mesh mesh)
  (check (eq :outcome-unknown (last-status port)))
  (check (notany (lambda (packet) (some (lambda (frame) (search (bytes "private-response") frame)) (second packet))) (sent port))))
;; A backwards wall-clock correction cannot revive an evicted expired request.
(let* ((now 1000) (calls 0) (port (make-instance 'synthetic-transport))
       (mesh (runtime port :clock (lambda () now)
                      :dispatch (lambda (peer req) (declare (ignore peer req)) (incf calls)
                                  (lambda () (make-result :ok))))))
  (start-mesh mesh) (deliver port (request)) (step-mesh mesh)
  (setf now 6000) (step-mesh mesh)
  (setf now 1000) (deliver port (request)) (step-mesh mesh)
  (check (= 1 calls)) (check (eq :deadline-exceeded (last-status port))))
(format t "~D final private-mesh core checks including clock rollback (synthetic).~%" *checks*)
