(load "runtime/package.lisp")
(load "runtime/host.lisp")
(let ((checks 0))
  (flet ((check (value) (incf checks) (assert value)))
    (let ((host (star.edge.host:make-host :platform "android")))
      (check (equal (star.edge.host:call-host host "start")
                    '(:status :unavailable :reason :runtime-not-attached)))
      (check (null (star.edge.host:host-capabilities host)))
      (check (equal (getf (star.edge.host:call-host host "eval") :reason)
                    :unknown-operation)))
    (let* ((seen nil) (allowed t) (advertised '("camera.photo"))
           (host (star.edge.host:make-host
                  :platform "meta-companion"
                  :backend (lambda (op payload cap)
                             (push (list op payload cap) seen) :forwarded)
                  :capabilities (lambda () advertised)
                  :authorize (lambda (cap payload) (declare (ignore cap payload)) allowed))))
      (check (eq :forwarded (star.edge.host:call-host host "status")))
      (check (eq :forwarded (star.edge.host:call-host host "dispatch" "opaque" "camera.photo")))
      (check (equal (first seen) '("dispatch" "opaque" "camera.photo")))
      (setf allowed nil)
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "camera.photo") :status)))
      (check (= 2 (length seen)))
      (setf allowed :truthy)
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "camera.photo") :status)))
      (setf allowed t advertised nil)
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "camera.photo") :status)))
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch") :status)))
      (check (= 2 (length seen))))
    (let ((host (star.edge.host:make-host :platform "wearos"
                 :backend (lambda (&rest args) (declare (ignore args)) :forwarded)
                 :capabilities (lambda () '("location.read")))))
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "location.read") :status))))
    (format t "~D Common Lisp host contract checks passed.~%" checks)))
