(load "runtime/package.lisp")
(load "runtime/host.lisp")
(load "runtime/outbox.lisp")
(let ((checks 0))
  (flet ((check (value) (incf checks) (assert value)))
    (let ((host (star.edge.host:make-host :platform "android")))
      (check (equal (star.edge.host:call-host host "start")
                    '(:status :unavailable :reason :runtime-not-attached)))
      (check (null (star.edge.host:host-capabilities host)))
      (check (equal (getf (star.edge.host:call-host host "eval") :reason)
                    :unknown-operation)))
    (let* ((seen nil) (allowed t) (advertised '("camera.photo"))
           (host (star.edge.host:make-host
                  :platform "meta-companion"
                  :backend (lambda (op payload cap)
                             (push (list op payload cap) seen) :forwarded)
                  :capabilities (lambda () advertised)
                  :authorize (lambda (cap payload) (declare (ignore cap payload)) allowed))))
      (check (eq :forwarded (star.edge.host:call-host host "status")))
      (check (eq :forwarded (star.edge.host:call-host host "dispatch" "opaque" "camera.photo")))
      (check (equal (first seen) '("dispatch" "opaque" "camera.photo")))
      (setf allowed nil)
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "camera.photo") :status)))
      (check (= 2 (length seen)))
      (setf allowed :truthy)
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "camera.photo") :status)))
      (setf allowed t advertised nil)
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "camera.photo") :status)))
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch") :status)))
      (check (= 2 (length seen))))
    (let ((host (star.edge.host:make-host :platform "wearos"
                 :backend (lambda (&rest args) (declare (ignore args)) :forwarded)
                 :capabilities (lambda () '("location.read")))))
      (check (eq :denied (getf (star.edge.host:call-host host "dispatch" nil "location.read") :status))))
    (let ((now 5000)
          (path #P"/tmp/starintel-edge-runtime-outbox.queue"))
      (let ((queue (star.edge.outbox:make-outbox :path path :clock (lambda () now))))
        (star.edge.outbox:outbox-ack queue "runtime-check")
        (check (eq :enqueued
                   (star.edge.outbox:outbox-enqueue queue "runtime-check" "sync" "payload")))
        (check (eq :deferred
                   (star.edge.outbox:outbox-retry queue "runtime-check" 5 "offline")))
        (check (null (star.edge.outbox:outbox-next-ready queue))))
      (incf now 5)
      (let* ((queue (star.edge.outbox:make-outbox :path path :clock (lambda () now)))
             (entry (star.edge.outbox:outbox-next-ready queue)))
        (check (equal "runtime-check" (getf entry :id)))
        (check (= 1 (getf entry :attempts)))
        (check (eq :acked (star.edge.outbox:outbox-ack queue "runtime-check")))))
    (format t "~D Common Lisp runtime contract checks passed.~%" checks)))
