;;;; Host-only real Lisp tests: sanitized failures and retained cleanup ownership.
(require :asdf)
(asdf:initialize-source-registry
 `(:source-registry (:directory ,(uiop:merge-pathnames* "runtime/" (uiop:getcwd))) :inherit-configuration))
(asdf:load-system :starintel-edge/runtime)
(star.edge.android:install-adapter-host)
(defvar *service-fail-stop* t)
(defvar *service-cleanup-events* nil)
(let* ((root (merge-pathnames (format nil "edge-safety-~D/" (random 1000000000)) (uiop:temporary-directory)))
       (init (merge-pathnames "init.lisp" root)) (checks 0))
  (ensure-directories-exist init)
  (labels ((check (value) (incf checks) (unless value (error "Safety check ~D failed" checks)))
           (write-init (text) (with-open-file (out init :direction :output :if-exists :supersede
                                                       :if-does-not-exist :create) (write-string text out)))
           (capture (fn)
             (let ((stream (make-string-output-stream)) (result nil))
               (let ((*standard-output* stream) (*error-output* stream) (*trace-output* stream))
                 (handler-bind ((warning (lambda (condition)
                                           (format stream "~A~%" condition)
                                           (muffle-warning condition))))
                   (setf result (handler-case (funcall fn)
                                  (serious-condition (condition)
                                    (format stream "~A~%" condition) :failed)))))
               (values result (get-output-stream-string stream)))))
    (unwind-protect
         (progn
           (write-init "(error \"INIT-SYNTHETIC-SECRET\")")
           (multiple-value-bind (result output) (capture (lambda () (star.edge.android:start-service-runtime init)))
             (check (eq result :failed))
             (check (not (search "INIT-SYNTHETIC-SECRET" output)))
             (check (search "android-service-initialization-failed" output)))
           (write-init "(setf star.edge.android:*service-components*
             (list (star.edge.runtime:make-component \"failing-start\"
                    :start (lambda () (error \"START-SYNTHETIC-SECRET\")) :stop (lambda () t))))")
           (multiple-value-bind (result output) (capture (lambda () (star.edge.android:start-service-runtime init)))
             (check (eq result :failed))
             (check (not (search "START-SYNTHETIC-SECRET" output)))
             (check (search "component-start" (string-downcase output)))
             (check (search "failing-start" output)))
           (check (null (star.edge.actors:current-actor-system)))
           (setf *service-fail-stop* t *service-cleanup-events* nil)
           (write-init "(in-package :cl-user)
(setf star.edge.android:*service-components*
 (list (star.edge.runtime:make-component \"first\" :start (lambda () t)
          :stop (lambda () (push :first *service-cleanup-events*)))
       (star.edge.runtime:make-component \"failing-stop\" :start (lambda () t)
          :stop (lambda () (push :failed *service-cleanup-events*)
                          (when *service-fail-stop* (error \"STOP-SYNTHETIC-SECRET\"))))
       (star.edge.runtime:make-component \"last\" :start (lambda () t)
          :stop (lambda () (push :last *service-cleanup-events*)))))")
           (star.edge.android:start-service-runtime init)
           (multiple-value-bind (result output)
               (capture (lambda () (star.edge.android:handle-request "service.stop" nil nil)))
             (check (search "managed-shutdown-failed" result))
             (check (not (search "STOP-SYNTHETIC-SECRET" output)))
             (check (search "component-stop" (string-downcase output)))
             (check (search "failing-stop" output)))
           (check (equal (reverse *service-cleanup-events*) '(:last :failed :first)))
           (check (eq :stop-failed (star.edge.runtime:runtime-state (star.edge.runtime:current-runtime))))
           (check (not (star.edge.android:service-ready-p)))
           (check (search "stop-failed" (star.edge.android:handle-request "service.status" nil nil)))
           (setf *service-fail-stop* nil)
           (check (star.edge.android:stop-service-runtime))
           ;; A real timeout condition must retain the actual actor-system handle.
           (write-init "(in-package :cl-user)")
           (star.edge.android:start-service-runtime init)
           (let ((owned (star.edge.actors:current-actor-system))
                 (shutdown (fdefinition 'sento.actor-context:shutdown)))
             (unwind-protect
                  (progn
                    (setf (fdefinition 'sento.actor-context:shutdown)
                          (lambda (&rest ignored) (declare (ignore ignored))
                            (error 'bordeaux-threads:timeout :length 1)))
                    (multiple-value-bind (result output)
                        (capture (lambda () (star.edge.android:handle-request "service.stop" nil nil)))
                      (check (search "managed-shutdown-failed" result))
                      (check (search "actor-stop" (string-downcase output)))
                      (check (search "condition redacted" output)))
                    (check (eq owned (star.edge.actors:current-actor-system)))
                    (check (eq :stop-failed (star.edge.runtime:runtime-state (star.edge.runtime:current-runtime))))
                    (check (not (star.edge.android:service-ready-p))))
               (setf (fdefinition 'sento.actor-context:shutdown) shutdown)))
           (check (star.edge.android:stop-service-runtime))
           (check (null (star.edge.actors:current-actor-system)))
           ;; A START timeout can leave an actual owned thread blocked. Strict
           ;; rollback must stop the attempted component before its dependencies,
           ;; retain it when bounded cleanup fails, and reject a second owner.
           (let ((star.edge.runtime:*require-confirmed-shutdown* t)
                 (star.edge.runtime:*redact-diagnostics* t)
                 (owner nil) (release nil) (starts 0) (events nil)
                 (lock (bordeaux-threads:make-lock "partial-start-test"))
                 (ready (bordeaux-threads:make-condition-variable)))
             (labels ((release-owner ()
                        (bordeaux-threads:with-lock-held (lock)
                          (setf release t)
                          (bordeaux-threads:condition-notify ready)))
                      (bounded-stop ()
                        (push :partial-stop events)
                        (let ((deadline (+ (get-internal-real-time)
                                           (/ internal-time-units-per-second 20))))
                          (loop while (and owner (bordeaux-threads:thread-alive-p owner)
                                           (< (get-internal-real-time) deadline))
                                do (sleep 0.001)))
                        (when (and owner (bordeaux-threads:thread-alive-p owner))
                          (error "PARTIAL-STOP-SYNTHETIC-SECRET"))
                        (when owner (bordeaux-threads:join-thread owner) (setf owner nil))))
               (unwind-protect
                    (let* ((partial
                             (star.edge.runtime:make-component "partial-owner"
                               :start (lambda ()
                                        (incf starts)
                                        (setf owner
                                          (bordeaux-threads:make-thread
                                            (lambda ()
                                              (bordeaux-threads:with-lock-held (lock)
                                                (loop until release
                                                  do (bordeaux-threads:condition-wait ready lock))))
                                            :name "synthetic-blocked-owner"))
                                        (error 'bordeaux-threads:timeout :length 1))
                               :stop #'bounded-stop))
                           (components
                             (list (star.edge.runtime:make-component "dependency"
                                     :start (lambda () (push :dependency-start events))
                                     :stop (lambda () (push :dependency-stop events)))
                                   partial
                                   (star.edge.runtime:make-component "unattempted"
                                     :start (lambda () (error "MUST-NOT-START"))
                                     :stop (lambda () (error "MUST-NOT-STOP")))))
                           (runtime nil))
                      (multiple-value-bind (result output)
                          (capture (lambda () (star.edge.runtime:start-runtime components)))
                        (setf runtime result)
                        (check (not (search "PARTIAL-STOP-SYNTHETIC-SECRET" output)))
                        (check (search "partial-owner" output)))
                      (check (eq :stop-failed (star.edge.runtime:runtime-state runtime)))
                      (check (eq :startup-failure (star.edge.runtime:runtime-stop-reason runtime)))
                      (check (star.edge.runtime:runtime-live-p runtime))
                      (check (and owner (bordeaux-threads:thread-alive-p owner)))
                      (check (equal (reverse events) '(:dependency-start :partial-stop :dependency-stop)))
                      (check (equal (star.edge.runtime::edge-runtime-components runtime) (list partial)))
                      (multiple-value-bind (result output)
                          (capture (lambda () (star.edge.runtime:start-runtime components)))
                        (declare (ignore output)) (check (eq result :failed)))
                      (check (= starts 1))
                      (release-owner)
                      (check (star.edge.runtime:stop-runtime runtime))
                      (check (null owner))
                      (check (null (star.edge.runtime:current-runtime)))
                      (check (eq :stopped (star.edge.runtime:runtime-state runtime)))
                      (check (equal (reverse events)
                                    '(:dependency-start :partial-stop :dependency-stop :partial-stop))))
                 (release-owner)
                 (when owner
                   (bordeaux-threads:with-timeout (2) (bordeaux-threads:join-thread owner)))
                 (star.edge.runtime:stop-runtime))))
           ;; Desktop default diagnostics retain condition detail; Android opts into redaction.
           (multiple-value-bind (result output)
               (capture (lambda ()
                          (let ((star.edge.runtime:*redact-diagnostics* nil))
                            (star.edge.runtime:warn-runtime-failure :desktop "desktop-probe"
                              (make-condition 'simple-error :format-control "DESKTOP-DETAIL")))))
             (declare (ignore result))
             (check (search "DESKTOP-DETAIL" output)))
           (format t "~D real Lisp cleanup/redaction checks passed; injected timeout, not Android/native shutdown proof.~%" checks))
      (setf *service-fail-stop* nil)
      (star.edge.android:stop-service-runtime)
      (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore))))
