/* Experimental owned-process transport. ECL is linked only into this child.
 * No managed boot, Lisp evaluator, signal-handler replacement or service policy.
 */
#define _GNU_SOURCE
#include "starintel_ecl_adapter.h"
_Static_assert(STARINTEL_ECL_ABI_VERSION == 1U, "Owned transport requires ABI 1");
#include "starintel_utf.h"
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <pthread.h>
#include <signal.h>
#include <stdint.h>
#include <stdlib.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <unistd.h>

static int read_exact(int fd, void *buffer, size_t length)
{
    size_t done = 0;
    while (done < length) {
        ssize_t n = read(fd, (char *)buffer + done, length - done);
        if (n > 0) done += (size_t)n;
        else if (n < 0 && errno == EINTR) continue;
        else return n == 0 && done == 0 ? 0 : -1;
    }
    return 1;
}

/* Suppress only a SIGPIPE generated by this thread's own failed pipe write.
 * Do not change ECL's handlers or mask any fault/protection signal. Preserve
 * both the previous mask and a SIGPIPE that was already pending on entry.
 */
static int write_exact(int fd, const void *buffer, size_t length)
{
    sigset_t pipe_signal, previous, pending;
    size_t done = 0;
    int result = -1, saved_errno = 0, was_pending;
    sigemptyset(&pipe_signal);
    sigaddset(&pipe_signal, SIGPIPE);
    if (pthread_sigmask(SIG_BLOCK, &pipe_signal, &previous) != 0) return -1;
    if (sigpending(&pending) != 0) goto restore;
    was_pending = sigismember(&pending, SIGPIPE);
    while (done < length) {
        ssize_t n = write(fd, (const char *)buffer + done, length - done);
        if (n > 0) done += (size_t)n;
        else if (n < 0 && errno == EINTR) continue;
        else {
            saved_errno = errno;
            if (n < 0 && errno == EPIPE && !was_pending) {
                struct timespec zero = {0, 0};
                while (sigtimedwait(&pipe_signal, NULL, &zero) < 0 && errno == EINTR) {}
            }
            goto restore;
        }
    }
    result = 0;
restore:
    if (pthread_sigmask(SIG_SETMASK, &previous, NULL) != 0) result = -1;
    errno = saved_errno;
    return result;
}

static int write_frame(int fd, const char *bytes, size_t length)
{
    const unsigned char header[4] = {
        (unsigned char)(length >> 24), (unsigned char)(length >> 16),
        (unsigned char)(length >> 8), (unsigned char)length
    };
    return write_exact(fd, header, sizeof header) ||
           (length && write_exact(fd, bytes, length)) ? -1 : 0;
}

static int valid_utf8(const char *bytes, size_t length)
{
    size_t cursor = 0;
    uint32_t scalar;
    while (cursor < length)
        if (!starintel_utf8_next(bytes, length, &cursor, &scalar) || scalar == 0)
            return 0;
    return 1;
}

/* A dead parent's unread input may still contain bytes, so check HUP even when
 * POLLIN is also set. Require pipes: this executable is not a terminal REPL.
 */
static int live_pipes(int input, int output)
{
    struct stat st;
    struct pollfd fds[2] = {{input, POLLIN, 0}, {output, POLLOUT, 0}};
    int n;
    if (fstat(input, &st) || !S_ISFIFO(st.st_mode) ||
        fstat(output, &st) || !S_ISFIFO(st.st_mode)) return 0;
    do { n = poll(fds, 2, 0); } while (n < 0 && errno == EINTR);
    return n >= 0 && !(fds[0].revents & (POLLHUP | POLLERR | POLLNVAL)) &&
           !(fds[1].revents & (POLLHUP | POLLERR | POLLNVAL));
}

int main(int argc, char **argv)
{
    static const char hello[] = "{\"transport\":\"starintel-owned/1\",\"abi\":1}";
    int input = -1, output = -1, nullfd = -1, booted = 0, code = 70;
    pid_t parent = getppid();
    char *error = NULL;
    if (argc != 2 || parent <= 1) return 64;
    /* Linux associates PDEATHSIG with the creating thread. The Java launcher
     * must keep its worker alive for the child's whole lifetime. */
    if (prctl(PR_SET_PDEATHSIG, SIGKILL) || getppid() != parent) return 70;
    input = fcntl(STDIN_FILENO, F_DUPFD_CLOEXEC, 3);
    output = fcntl(STDOUT_FILENO, F_DUPFD_CLOEXEC, 3);
    if (input < 0 || output < 0) goto done;
    nullfd = open("/dev/null", O_RDONLY | O_CLOEXEC);
    if (nullfd < 0 || dup2(nullfd, STDIN_FILENO) < 0 ||
        dup2(STDERR_FILENO, STDOUT_FILENO) < 0) goto done;
    close(nullfd); nullfd = -1;
    if (getppid() != parent || !live_pipes(input, output) ||
        starintel_ecl_abi_version() != STARINTEL_ECL_ABI_VERSION) goto done;
    if (starintel_ecl_start(argv[1], &error) != 0) {
        starintel_ecl_free(error); /* Never expose a trusted-init condition. */
        goto done;
    }
    starintel_ecl_free(error);
    booted = 1;
    if (write_frame(output, hello, sizeof hello - 1)) goto done;
    for (;;) {
        unsigned char header[4];
        char *request, *response;
        size_t response_length;
        uint32_t length;
        int read_status = read_exact(input, header, sizeof header);
        if (read_status == 0) { code = 0; break; } /* Clean idle EOF. */
        if (read_status < 0) { code = 65; break; }
        length = ((uint32_t)header[0] << 24) | ((uint32_t)header[1] << 16) |
                 ((uint32_t)header[2] << 8) | header[3];
        if (length == 0) {
            starintel_ecl_stop(); booted = 0;
            code = write_frame(output, NULL, 0) ? 74 : 0;
            break;
        }
        if (length > STARINTEL_ECL_MAX_REQUEST_BYTES) { code = 65; break; }
        request = malloc((size_t)length + 1);
        if (!request) break;
        if (read_exact(input, request, length) != 1 || !valid_utf8(request, length)) {
            free(request); code = 65; break;
        }
        request[length] = 0;
        response = starintel_ecl_request(request);
        free(request);
        if (!response) break;
        response_length = starintel_bounded_strlen(response, STARINTEL_ECL_MAX_RESPONSE_BYTES + 1u);
        if (response_length == 0 || response_length > STARINTEL_ECL_MAX_RESPONSE_BYTES ||
            !valid_utf8(response, response_length)) {
            starintel_ecl_free(response); break;
        }
        int wrote = write_frame(output, response, response_length);
        starintel_ecl_free(response);
        if (wrote) break;
    }
done:
    if (booted) starintel_ecl_stop();
    if (nullfd >= 0) close(nullfd);
    if (input >= 0) close(input);
    if (output >= 0) close(output);
    return code;
}
